Feature/generate receipt
CAFECA-IO/Political-Donations-Crawler pull request #3
Opened 2024-09-11 10:03 UTC by TzuHanLiang

### DEVELOP

- [x] 新增 table： receipt_sync
- [x] 新增 generate receipt daemon

### CHECK LIST

- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new recursive: 0
- high risk: 0
- new sql: 5
    - src/receipt_generator.ts
        - ln28
        - ln227
        - ln240
        - ln247
        - ln253
- new loop: 1
    - ln252-277
- new Library: 2
    - @pdf-lib/fontkit
    - pdf-lib
- new Class / Component: 0

2024-09-11 10:53 UTC, Luphia requested changes

2024-09-11 10:53 UTC, Luphia commented on prisma/donations.db
- remove db file

2024-09-11 10:53 UTC, Luphia commented on src/assets/fonts/SourceHanSansTW-Regular.otf
- The file name must comply with the naming conventions

2024-09-11 10:53 UTC, Luphia commented on src/receipt_generator.ts
- The comment format must be followed

2024-09-12 02:45 UTC, TzuHanLiang commented on src/receipt_generator.ts
fixed

2024-09-12 06:57 UTC, Luphia approved these changes
- no bug found

2024-09-12 06:57 UTC, merged